services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    develop:
      watch:
        - action: sync
          path: ./frontend/
          target: /app/
          ignore:
            - ./frontend/node_modules/
        - action: rebuild
          path: ./frontend/package.json

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://mongo:27017/events_db
      - POSTGRES_URI=postgres://username:password@postgres:5432/mydb?sslmode=disable
    depends_on:
      - mongo
      - postgres
    develop:
      watch:
        - action: rebuild
          path: ./backend

  rust_backend:
    build: ./rust_backend
    ports:
      - "8081:8081"
    environment:
      - POSTGRES_URI=postgres://username:password@postgres:5432/mydb?sslmode=disable
    depends_on:
      - postgres
    develop:
      watch:
        - action: rebuild
          path: ./rust_backend

  mongo:
    image: mongo:5.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  postgres_data:
